services:
  - type: worker  # ✅ 웹에서 worker로 변경
    name: rsi-sma-trader-bot
    env: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python autotrade.py --backtest
    autoDeploy: true
    envVars:
      - key: TELEGRAM_TOKEN
        sync: true
      - key: TELEGRAM_CHAT_ID
        sync: true
      - key: SEND_ALERT
        value: "True"
